* 1. population

A population is a localized group of organisms

* 2. light energy

The main source of energy for producers in an ecosystem

* 3. negative feedback

Insulin secretion by the pancreas to lower glucose levels in the blood

* 4. archaea (prokaryotic cell)

Cells that utilize DNA, but don't have dna encased within a nuclear envelope

* 5. bacteria & archaea

The 2 different domains of prokaryotic cells

* 6. evolution

The core theme of biology. A framework within which all biological investigation makes sense.

* 7. control group

Provides a basis for knowing if a particular result is due to the variable being tested.

* 8. Technology

The application of scientific knowledge for some specific purpose.

* 9. systems biology

An approach to model dynamic behavior of whole biological systems

* 10. protists & bacteria

Protists differ in domain since they are eukaryotic cells

* 11. biological hierarchy & organization

least complex -> most complex
molecule, organelle, cell, tissue, organ, organ system, organism, population, community, ecosystem

* 12. childbirth

Is an example of positive feedback

* 13. unity in diversity

- all organisms use the same genetic code
- cilia & flagella in all eukaryotes have the same basic structure
- dna structure is the same in all organisms
- forelimbs of all mammals have the same basic structure

* 14. common ancestry of life

- near universality of the genetic core

* 15. natural selection

- requires genetic variation
- results in descent with modification
- involves differential reproductive success

* 16. global warming

- we need to limit the burning of fossil fuels and regulate loss of forested areas

* 17. filamentous organism, decomposing organic matter, no chloroplasts

eukarya, fungi

* 18. evolutionary success

- an organism that dies after 5 days, but leaves 10 offspring all survive to reproduce

* 19. controlled experiment

at least 2 groups, one of which doesn not receive the experimental treatment

* 20. community

would include all the organisms in our campus

* 21. life hierarchy

nervous system, brain, nervous tissue, nerve cell

* 22. unity among all organisms

the structure & function of dna

* 23. a controlled experiment

tests experimental & control groups in parallel

* Questions on Ch. 1 quiz

** question 7

Includes 2 different examples. Both are answers, not a clear
question. I'm thinking the answer catalytic feedback accounts for both
positive & negative feedback. The quiz only accepts negative feedback.

** question 6

I don't think this is in the book.
