* 1. pre-test question 1

Most organic componds contain carbon and ____.

1. +phosphate+
2. +nitrogen+
3. +sulfur+
4. *hydrogen*
5. +oxygen+

* 2. question 1

the element present in all organic molecules is

1. +phosphorous+
2. +oxygen+
3. +hydrogen+
4. +nitrogen+
5. *carbon*

* 3. pre-test question 4

The large diversity of shapes of biological molecules is possible
because of the extensive presence of ____ in the molecules

1. +sulfur+
2. +hydrogen+
3. *carbon*
4. +nitrogen+
5. +oxygen+

* 4. pre-test question 7

Which of the following best describes cis-trans isomers?

1. +they differ in the arrangement of covalent bonds and in covalent partners.+
2. +they are long chains of hydrogen and carbon atoms.+
3. +they have the same number of atoms of the same elements but different structures+
4. *they differ in their spatial arrangement around inflexible double bonds.*
5. +they are mirror images of each other+

* 5. pre-test question 8

Citric acid makes lemons taste sour. Which of the following is a
functional group that would cause a molecule such as citric acid to be
acidic?

1. *carboxyl*
2. +hydrocarbon+
3. +amino+
4. +carbonyl+
5. +hydroxyl+

* 6. pre-test question 10

What functional group is commonly used in cells to transfer energy from
one organic molecule to another?

1. +sulfhydryl+
2. *phosphate*
3. +amino+
4. +hydroxyl+
5. +carboxyl+

* 7. question 3

MAKE CONNECTIONS Which chemical group is most likely to be responsible
for an organic molecule behaving as a base (see Concept 3.3, p. 53 in
your textbook)?

1. +carbonyl+
2. +phosphate+
3. +carboxyl+
4. +hydroxyl+
5. *amino*

* 8. question 61

which molecule shown above is a thiol?

1. +a+
2. *b* (Contains a sulfhydryl group -SH)
3. +c+
4. +d+
5. +e+

* 9. question 21

a compound contains hydroxl groups as its predominant functional
group. Which of the following statements is true concerning this
compound?

1. +it should dissolve in a nonpolar solvent+
2. +it lacks an asymmetric carbon, and it is probably a fat or lipid+
3. +it is hydrophobic+
4. +it won't form hydrogen bonds with water+
5. *it should dissolve in water*

* 10. question 41

which of the structures illustrated above contains a carbonyl functional
group?

1. +a+
2. +c & d+
3. +c+
4. *d* (C = O)
5. +c & e+
