* Environmental consequences of the use of batteries in low carbon systems: The impact of battery pr  :PRINTED:PDF:EBSCO:CITED:2012:
McManus, M.C. "Environmental Consequences Of The Use Of Batteries In Low Carbon Systems: The Impact Of Battery Production." Applied Energy 93.(2012): 288-295. Academic Search Premier. Web. 14 June 2012.
http://search.ebscohost.com/login.aspx?direct=true&db=aph&AN=73570459&site=ehost-live
http://microgen11.supergen-hidef.org/microgenII/CD/full_papers/p114v2.pdf

McManus, M.C. "Environmental Consequences Of The Use Of Batteries In Low Carbon Systems: The Impact Of Battery Production." Applied Energy 93.(2012): 288-295. Academic Search Premier. Web. 21 June 2012.

* The Post Carbon Reader: Managing the 21st Century's Sustainability Crises  :BOOK:CITED:
http://www.amazon.com/The-Post-Carbon-Reader-Sustainability/dp/0970950063
http://catdir.loc.gov/catdir/enhancements/fy1112/2010931734-b.html
1 copy available at Redwood Campus Library.
* Scarce metals - Applications, supply risks and need for action  :PDF:SEARCH:PRINTED:
http://ewasteguide.info/files/W%C3%A4ger_2012_Politeia.pdf

http://www.politeia-centrostudi.org/notiziepoliteia.html
* Production and Use of Biodegradable Materials for Incorporation in a Non-Toxic, Eco-Friendly Battery  :PDF:PRINTED:JSTOR:2007:CITED:
http://www.jstor.org/stable/20476301?seq=1&Search=yes&searchText=environment&searchText=battery&list=hide&searchUri=%2Faction%2FdoBasicSearch%3FQuery%3Dbattery%2Benvironment%26gw%3Djtx%26acc%3Don%26prq%3Dsolar%2Btechnology%2Benvironment%26Search%3DSearch%26hp%3D25%26wc%3Don&prevSearch=&item=1&ttl=17817&returnArticleService=showFullText&resultsServiceName=null

Production and Use of Biodegradable Materials for Incorporation in a Non-Toxic, Eco-Friendly Battery
Evan Plous
Transactions of the Kansas Academy of Science (1903-) , Vol. 110, No. 1/2 (Spring, 2007), pp. 116-124
Published by: Kansas Academy of Science
Article Stable URL: http://www.jstor.org/stable/20476301

* Environmental Technologies and Competitive Advantage  :PDF:JSTOR:1995:PRINTED:
Environmental Technologies and Competitive Advantage
Paul Shrivastava
Strategic Management Journal , Vol. 16, Special Issue: Technological Transformation and the New Competitive Landscape (Summer, 1995), pp. 183-200
Published by: John Wiley & Sons
Article Stable URL: http://www.jstor.org/stable/2486775

http://www.jstor.org/stable/2486775?&Search=yes&searchText=batteries&searchText=impact&searchText=environmental&list=hide&searchUri=%2Faction%2FdoBasicSearch%3FQuery%3Dbatteries%2Benvironmental%2Bimpact%26gw%3Djtx%26acc%3Don%26prq%3Dbatteries%2Benvironment%26Search%3DSearch%26hp%3D25%26wc%3Don&prevSearch=&item=3&ttl=2093&returnArticleService=showFullText
* The Duality of Technology: Rethinking the Concept of Technology in Organizations  :PDF:JSTOR:1992:PRINTED:
The Duality of Technology: Rethinking the Concept of Technology in Organizations
Wanda J. Orlikowski
Organization Science , Vol. 3, No. 3, Focused Issue: Management of Technology (Aug., 1992), pp. 398-427
Published by: INFORMS
Article Stable URL: http://www.jstor.org/stable/2635280

http://www.jstor.org/stable/2635280?&Search=yes&searchText=technology&searchText=impact&searchText=environmental&list=hide&searchUri=%2Faction%2FdoBasicSearch%3FQuery%3Dtechnology%2Benvironmental%2Bimpact%26gw%3Djtx%26acc%3Don%26prq%3Dbatteries%2Benvironmental%2Bimpact%26Search%3DSearch%26hp%3D25%26wc%3Don&prevSearch=&item=3&ttl=84908&returnArticleService=showFullText
* Converting Technology to Mitigate Environmental Damage  :PDF:JSTOR:2004:PRINTED:CITED:
Converting Technology to Mitigate Environmental Damage
Maurice D. Levi and Barrie R. Nault
Management Science , Vol. 50, No. 8 (Aug., 2004), pp. 1015-1030
Published by: INFORMS
Article Stable URL: http://www.jstor.org/stable/30046127

http://www.jstor.org/stable/30046127?&Search=yes&searchText=technology&searchText=impact&searchText=environmental&list=hide&searchUri=%2Faction%2FdoBasicSearch%3FQuery%3Dtechnology%2Benvironmental%2Bimpact%26gw%3Djtx%26acc%3Don%26prq%3Dbatteries%2Benvironmental%2Bimpact%26Search%3DSearch%26hp%3D25%26wc%3Don&prevSearch=&item=4&ttl=84908&returnArticleService=showFullText


* UPS Saved Fuel by Turning Right 			       :2007:WEBSITE:
http://pressroom.ups.com/About+UPS/UPS+Leadership/Speeches/D.+Scott+Davis/Right+Turn+at+the+Right+Time

* Walmart Sets Goal to Sell 100 Million CFL Bulbs 	       :2007:WEBSITE:
http://www.walmartstores.com/pressroom/news/6756.aspx
* Green technology foresight of high technology: a social shaping of technology approach to the analysis of hopes and hypes.  :EBSCO:2009:PDF:SCHOLARLY:CITED:
http://web.ebscohost.com/ehost/detail?sid=e6dc8be0-488b-4cae-8fc9-631e5ec03e5c%40sessionmgr12&vid=3&hid=12&bdata=JnNpdGU9ZWhvc3QtbGl2ZQ%3d%3d#db=aph&AN=37265512

Jørgensen, Michael Søgaard, and Ulrik Jørgensen. "Green Technology Foresight Of High Technology: A Social Shaping Of Technology Approach To The Analysis Of Hopes And Hypes." Technology Analysis & Strategic Management 21.3 (2009): 363-379. Academic Search Premier. Web. 19 June 2012.


* order
heinberg
jorgensen
levi
mcmanus
plous
ups
wal-mart
