* A Modest Proposal - p. 755-760
** 1) How does this relate to the structure of a modern proposal? 

The author, Swift, provides us with several points of information that
are used as examples of a problem. They have a large poor population
with many kids and youth. He then offers a solution, eat babies, as a
his core proposal. He proceeds to step through several points that
show why this proposal is beneficial. This is similar to the structure
of a modern proposal by offering a solution to a problem through
several steps of support or reasoning.

** 2) What is literaly propposed? What is meant? What strategies?

Swift literaly proposed the benefits of eating children to fix
economical issues. The likely satirical meaning behind this would be
that we either need to restrict over population in some way or
reconsider the way we percieve lower class women, families, and
children. Swift downplays negative emotions, provides a lot of logical
conclusions to his proposal, and regualarly refers to friends of his
in an authoritative sense to make this proposal feel real.

** 3) Is it really a proposal? If not, does it achieve some other purpose? What genre based on purpose?

It is strictly speaking a proposal, though satirical intention, to me
makes it feel like more of a rant. One could easily say in fewer
words, "Let's eat babies like livestock," however using the
form of a sincere proposal allows him to seriously extrapolate on
consequences both positive and negative that would relate to the issue.
